changesetBaseRefs:
  - 'main'
  - 'origin/main'
  - 'upstream/main'

enableGlobalCache: true

nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: '@yarnpkg/plugin-version'

yarnPath: .yarn/releases/yarn-3.0.0.cjs
