name: main
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  install:
    name: Install Dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: fernandopasik/actions/setup-node@main
  #<% if (checkFormat) { %>
  check-format:
    name: Check Format
    runs-on: ubuntu-latest
    needs: install
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: fernandopasik/actions/setup-node@main
      - name: Check Format
        run: <% if (yarn) { %>yarn<% } else { %>npm run<% } %> format:check
  #<% } %>
  #<% if (lint) { %>
  lint:
    name: Lint
    runs-on: ubuntu-latest
    needs: install
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: fernandopasik/actions/setup-node@main
      - name: Lint
        run: <% if (yarn) { %>yarn lint<% } else { %>npm run lint --<% } %> --format junit -o reports/lint-results.xml
      - name: Upload Report
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: lint-results
          path: reports/lint-results.xml
  #<% } %>
  #<% if (checkTypes) { %>
  check-types:
    name: Check Typescript Types
    runs-on: ubuntu-latest
    needs: install
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: fernandopasik/actions/setup-node@main
      - name: Check Typescript Types
        run: <% if (yarn) { %>yarn<% } else { %>npm run<% } %> check-types
  #<% } %>
  #<% if (unitTests) { %>
  unit-test:
    name: Unit Tests
    runs-on: ubuntu-latest
    needs: install
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: fernandopasik/actions/setup-node@main
      - name: Unit Tests
        run: <% if (yarn) { %>yarn test:coverage<% } else { %>npm run test:coverage --<% } %> --ci --reporters=default --reporters=jest-junit
        env:
          JEST_JUNIT_OUTPUT_FILE: 'reports/unit-test-results.xml'
      - name: Upload Report to Codecov
        uses: codecov/codecov-action@v3
        if: always()
      - name: Upload Report
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: unit-test-results
          path: reports/unit-test-results.xml
  #<% } %>
  #<% if (e2eTests) { %>
  e2e-test:
    name: E2E Tests
    runs-on: ubuntu-latest
    needs: install
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: fernandopasik/actions/setup-node@main
      - name: E2E Tests
        run: <% if (yarn) { %>yarn test:e2e<% } else { %>npm run test:e2e --<% } %> --ci --reporters=default --reporters=jest-junit
        env:
          JEST_JUNIT_OUTPUT_FILE: 'reports/e2e-test-results.xml'
      - name: Upload Report
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: e2e-test-results
          path: reports/e2e-test-results.xml
  #<% } %>
  #<% if (build) { %>
  build:
    name: Build
    runs-on: ubuntu-latest
    needs:
      #<% if (checkFormat) { %>
      - check-format
      #<% } %>
      #<% if (lint) { %>
      - lint
      #<% } %>
      #<% if (checkTypes) { %>
      - check-types
      #<% } %>
      #<% if (unitTests) { %>
      - unit-test
      #<% } %>
      #<% if (e2eTests) { %>
      - e2e-test
      #<% } %>
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: fernandopasik/actions/setup-node@main
      - name: Build
        run: <% if (yarn) { %>yarn<% } else { %>npm run<% } %> build
      #<% } %>
      #<% if (checkSize) { %>
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: bundle
          path: <%= name %>.min.*
  size:
    name: Check Size
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: fernandopasik/actions/setup-node@main
      - name: Download Build Artifact
        uses: actions/download-artifact@v3
        with:
          name: bundle
      - name: Check Size
        run: <% if (yarn) { %>yarn<% } else { %>npm run<% } %> size
  #<% } %>
