name: main
on:
  push:
    branches:
      - master
jobs:
  install:
    name: Install Dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          check-latest: true
          cache: 'yarn'
      - run: yarn --immutable
  pre-build:
    name: ${{ matrix.name }}
    strategy:
      matrix:
        include:
          - name: Check Format
            task: yarn format:check
          - name: Lint
            task: yarn lint
          - name: Check Typescript Types
            task: yarn check-types
          - name: Unit Tests
            task: yarn test:coverage
    runs-on: ubuntu-latest
    needs: [install]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          check-latest: true
          cache: 'yarn'
      - run: yarn --immutable
      - run: ${{ matrix.task }}
  build:
    name: Build
    runs-on: ubuntu-latest
    needs: [pre-build]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          check-latest: true
          cache: 'yarn'
      - run: yarn --immutable
      - run: yarn build
